# SEM1 2021/2022
# CSCI 2304 SECTION 2 INTELLIGENT SYSTEMS
# ASSIGNMENT 1
# TITLE: GUESS THE MOVIE
# INSTRUCTOR: ASSOC. PROF. TS. DR. AMELIA RITAHANI BINTI ISMAIL
# DONE BY: AHMED FAISAL 1921967 & MUHAMMAD ISMAIL 1922235
from game import Game

g = Game()

while g.running:  # Game loop
    g.curr_display.display()
